<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Catálogo de Usuários</title>

  <!-- Tell the browser to be responsive to screen width -->
  <?= $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bower_components/Ionicons/css/ionicons.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('plugins/iCheck/square/blue.css'))
        ?>

<style type="text/css">
  .msg-error{
    color: red;
  }
</style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Catálogo de Usuários</b>
  </div>
  <!-- /.login-logo -->
  <?php if (!empty($this->message)): ?>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <!-- <strong>Warning!</strong>--> <?php echo $this->message ?>
  </div>
  <?php endif; ?>
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="/administrator/auth/login/<?php echo $this->paramsRoute;?>" method="post">
      <div class="form-group has-feedback">
        <!-- <input type="email" class="form-control" placeholder="Email"> -->
        <?php echo $this->formElement($this->form->get('email')); ?>
        <span class="msg-error"><?php echo $this->formElementErrors($this->form->get('email'));?></span>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <!-- <input type="password" class="form-control" placeholder="Password"> -->
        <?php echo $this->formElement($this->form->get('password')); ?>
        <span class="msg-error"><?php echo $this->formElementErrors($this->form->get('password'));?></span>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <!-- <input type="checkbox">  -->
              <?php echo $this->formCheckbox($this->form->get('remember')); ?> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <!--
    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div>
  -->
    <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- Scripts -->
<!-- jQuery 3 -->
<!-- Bootstrap 3.3.7 -->
<!-- iCheck -->
<?= $this->headScript()
    ->prependFile($this->basePath('plugins/iCheck/icheck.min.js'))
    ->prependFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('bower_components/jquery/dist/jquery.min.js'))
?>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>
