<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Catálogo de Usuários</title>

  <!-- Tell the browser to be responsive to screen width -->
  <?= $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bower_components/Ionicons/css/ionicons.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('plugins/iCheck/square/blue.css'))
        ?>

<style type="text/css">
  .msg-error{
    color: red;
  }
</style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Catálogo de Usuários</b>
  </div>
  <!-- /.login-logo -->
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Sessão expirada!</strong> <a href="/administrator/auth/login/<?php echo $this->idClient;?>">Efetue um novo login</a>
  </div>
</div>
</body>
</html>
