<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <?= $this->headTitle('Catálogo de Usuários')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- DataTables -->
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('bower_components/Ionicons/css/ionicons.min.css'))
            ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'))
        ?>


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS fixed TO GET A FIXED HEADER AND SIDEBAR LAYOUT -->
<!-- the fixed layout is not compatible with sidebar-mini -->
<body class="hold-transition skin-blue fixed sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="../../administrator/marks" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>Catálogo</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Catálogo</b> Usuários</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Locate US -->
          <li class="dropdown messages-menu">
            <?php
            if (strpos($this->controller, "\\") === false) {
              if ($this->action !== 'index') {
                $currentUrl = "/administrator/".$this->controller.'/'.$this->action;
              } else {
                $currentUrl = "/administrator/".$this->controller;
              }
            } else {
              $currentUrl = '/administrator';
            }
            ?>

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- <img src="../../dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
              <span class="hidden-xs">Bem vindo</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
               <!-- <img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"> -->

                <p>
                  Bem vindo - administrador
                  <small>Login válido</small>
                </p>
              </li>
              <!-- Menu Body -->
              <!-- <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div> -->
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Meus dados</a>
                </div>
                <div class="pull-right">
                  <a href="/administrator/auth/logout" class="btn btn-default btn-flat">Sair</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- =============================================== -->

  <?php echo $this->partial('partial/menu.phtml');?>

  <!-- scripts default -->
  <!-- jQuery 3 -->
  <!-- Bootstrap 3.3.7 -->
  <!-- FastClick -->
  <!-- AdminLTE App -->
<!--  <script src="../../bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script> -->
  <?php
        $this->headScript()
            ->prependFile($this->basePath() . '/dist/js/adminlte.min.js')
            ->prependFile($this->basePath() . '/bower_components/fastclick/lib/fastclick.js')
            ->prependFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js');
   ?>
  <!-- =============================================== -->
<!-- ./wrapper -->
<?php
    echo $this->headScript();
?>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

<?php
//TRATA RETORNO DA API
$children = $this->viewModel()->getCurrent()->getChildren();
foreach($children as $child) {
    if ($child->captureTo() === 'content') {
        break;
    }
}
$arrResponse = isset($child->response) ? $child->response : array();
?>

<?php if (!empty($arrResponse) && $arrResponse['code'] !== 0) : ?>
    <!-- Main content -->
    <section class="content">
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-warning"></i> <?= $arrResponse['type'] ?>!</h4>
                <?= $arrResponse['message'] ?>
      </div>
<?php endif; ?>
        <?= $this->content ?>
        <!-- MODAL LOADING  -->
        <div class="modal fade" id="modal-load" backdrop='false'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-load-title" id="title-modal">Por favor, aguarde um instante</h4>
                    </div>
                    <div class="modal-body">
                        <div class="text-center" id="modal-load-div-loading">
                            <img src="/img/loading-medium.gif">
                            <br>
                            <span>Carregando...</span>
                        </div>
                    </div>
                </div>
            <!-- /.modal-content -->
            </div>
        <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->

     <!-- <div class="callout callout-info">
        <h4>Tip!</h4>

        <p>Add the fixed class to the body tag to get this layout. The fixed layout is your best option if your sidebar
          is bigger than your content because it prevents extra unwanted scrolling.</p>
      </div>

      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Title</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          Start creating your amazing application!
        </div>

        <div class="box-footer">
          Footer
        </div>

      </div>
      -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2018-<?= date('Y'); ?> <a href="#1">Catálogo de usuários</a>.</strong> Todos os direitos reservados.
  </footer>


  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>

<!-- Config modal load -->
<script type="text/javascript">
    $("#modal-load").modal({
        keyboard: false,
        backdrop: false,
        show: false
    });
</script>
<!-- === -->
</body>
</html>
